export interface ExperienceProps {
    id: number;
    img: string,
    role: string;
    grade?: string;
    company: string;
    date: string;
    desc: string;
    skills?: string[];
  }
  
  const experiences: ExperienceProps[] = [
    {
        id: 0,
        img: "kul.png",
        role: "DevOps & Fullstack Engineering Intern",
        grade: "5",
        company: "Flipr Inovations Pvt. Ltd.",
        date: "Aug 2023 - July 2023",
        desc: "Working on Flipr Platforms, managing DevOps, and streamlining the process with automation.",
        skills: [
          "Docker",
          "Terraform",
          "AWS",
          "EC2",
          "Portainer",
          "Nginx",
          "JavaScript",
          "TypeScript",
          "Node Js",
          "Next Js",
        ],
        // doc: "https://media.licdn.com/dms/image/D4D2DAQFlp60ZqHuaFQ/profile-treasury-image-shrink_1280_1280/0/1691180828512?e=1692381600&v=beta&t=mM5Y_NE5EPlQhez5FAN6NLVSKcO_Ojt_9Gq3mnFGkAQ",
      },
      {
        id: 1,
        img: "kul.png",
        role: "DevOps & Fullstack Engineering Intern",
        grade: "5",
        company: "Flipr Inovations Pvt. Ltd.",
        date: "Aug 2023 - July 2023",
        desc: "Working on Flipr Platforms, managing DevOps, and streamlining the process with automation.",
        skills: [
          "Docker",
          "Terraform",
          "AWS",
          "EC2",
          "Portainer",
          "Nginx",
          "JavaScript",
          "TypeScript",
          "Node Js",
          "Next Js",
        ],
        // doc: "https://media.licdn.com/dms/image/D4D2DAQFlp60ZqHuaFQ/profile-treasury-image-shrink_1280_1280/0/1691180828512?e=1692381600&v=beta&t=mM5Y_NE5EPlQhez5FAN6NLVSKcO_Ojt_9Gq3mnFGkAQ",
      },
      {
        id: 2,
        img: "kul.png",
        role: "DevOps & Fullstack Engineering Intern",
        grade: "5",
        company: "Flipr Inovations Pvt. Ltd.",
        date: "Aug 2023 - July 2023",
        desc: "Working on Flipr Platforms, managing DevOps, and streamlining the process with automation.",
        skills: [
          "Docker",
          "Terraform",
          "AWS",
          "EC2",
          "Portainer",
          "Nginx",
          "JavaScript",
          "TypeScript",
          "Node Js",
          "Next Js",
        ],
        // doc: "https://media.licdn.com/dms/image/D4D2DAQFlp60ZqHuaFQ/profile-treasury-image-shrink_1280_1280/0/1691180828512?e=1692381600&v=beta&t=mM5Y_NE5EPlQhez5FAN6NLVSKcO_Ojt_9Gq3mnFGkAQ",
      },
      {
        id: 3,
        img: "kul.png",
        role: "DevOps & Fullstack Engineering Intern",
        grade: "5",
        company: "Flipr Inovations Pvt. Ltd.",
        date: "Aug 2023 - July 2023",
        desc: "Working on Flipr Platforms, managing DevOps, and streamlining the process with automation.",
        skills: [
          "Docker",
          "Terraform",
          "AWS",
          "EC2",
          "Portainer",
          "Nginx",
          "JavaScript",
          "TypeScript",
          "Node Js",
          "Next Js",
        ],
        // doc: "https://media.licdn.com/dms/image/D4D2DAQFlp60ZqHuaFQ/profile-treasury-image-shrink_1280_1280/0/1691180828512?e=1692381600&v=beta&t=mM5Y_NE5EPlQhez5FAN6NLVSKcO_Ojt_9Gq3mnFGkAQ",
      },
      {
        id: 4,
        img: "kul.png",
        role: "DevOps & Fullstack Engineering Intern",
        grade: "5",
        company: "Flipr Inovations Pvt. Ltd.",
        date: "Aug 2023 - July 2023",
        desc: "Working on Flipr Platforms, managing DevOps, and streamlining the process with automation.",
        skills: [
          "Docker",
          "Terraform",
          "AWS",
          "EC2",
          "Portainer",
          "Nginx",
          "JavaScript",
          "TypeScript",
          "Node Js",
          "Next Js",
        ],
        // doc: "https://media.licdn.com/dms/image/D4D2DAQFlp60ZqHuaFQ/profile-treasury-image-shrink_1280_1280/0/1691180828512?e=1692381600&v=beta&t=mM5Y_NE5EPlQhez5FAN6NLVSKcO_Ojt_9Gq3mnFGkAQ",
      },
  ];
  
  export default experiences;