export const projectStyles = [
    {
        backgroundColors: "rgb(12, 12, 29)",
        buttonBackground: "bg-[#5b21b6]",
        buttonBackgroundHover: "hover:bg-[#471a8f]",
        underlineColors: "decoration-[#5b21b6]",
        closeTag: "text-[#5b21b6]",
        border: "bg-[conic-gradient(#7a3ae1_20deg,transparent_120deg)]",
    },
    {
        backgroundColors: "rgb(43, 22, 67)",
        buttonBackground: "bg-[#764ef9]",
        buttonBackgroundHover: "hover:bg-[#4f36a3]",
        underlineColors: "decoration-[#764ef9]",
        closeTag: "text-[#764ef9]",
        border: "bg-[conic-gradient(#9375f7_20deg,transparent_120deg)]",
    },
    {
        backgroundColors: "rgb(27, 26, 33)",
        buttonBackground: "bg-[#0057be]",
        buttonBackgroundHover: "hover:bg-[#023c82]",
        underlineColors: "decoration-[#0057be]",
        closeTag: "text-[#0057be]",
        border: "bg-[conic-gradient(#4191f2_20deg,transparent_120deg)]",
    },
    {
        backgroundColors: "rgb(15, 17, 23)",
        buttonBackground: "bg-[#6b21a8]",
        buttonBackgroundHover: "hover:bg-[#4a1576]",
        underlineColors: "decoration-[#6b21a8]",
        closeTag: "text-[#6b21a8]",
        border: "bg-[conic-gradient(#9b3ce9_20deg,transparent_120deg)]",
    },
    {
        backgroundColors: "var(--neutral-900)",
        buttonBackground: "bg-[#0057be]",
        buttonBackgroundHover: "hover:bg-[#033f88]",
        underlineColors: "decoration-[#0057be]",
        closeTag: "text-[#0057be]",
        border: "bg-[conic-gradient(#4191f2_20deg,transparent_120deg)]",
    },
    {
        backgroundColors: "rgb(12, 12, 29)",
        buttonBackground: "bg-[#6b21a8]",
        buttonBackgroundHover: "hover:bg-[#4d147b]",
        underlineColors: "decoration-[#6b21a8]",
        closeTag: "text-[#6b21a8]",
        border: "bg-[conic-gradient(#7a3ae1_20deg,transparent_120deg)]",
    },
];